node_detail_view.settings:
  type: config_object
  label: 'Default View'
  mapping:
    default_view:
      type: config_object
      label: 'Default View'
    info_block_class:
      type: config_object
      label: 'Info block class value'